---
name: cmpsc-101-fall-2018-practical8
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/main:
    java:
        practicaleight/list/DoublyLinkedList.java:
            --multi 29 --language Java
            --fragment "println(" --count 2
            --fragment "public static void" --count 1 --exact
            --fragment "TODO" --count 0 --exact
# --> check the number of commits beyond a threshold
--commits 14
# --> check that the program executes correctly
--command "gradle -q --console plain run" --executes
--command "gradle -q --console plain run" --count 4 --exact
